### ISSUE TITLE
Diagrama de casos de uso

### ISSUE THREAD

**Issue by Lflickr** [Milenxsz/ES2#15]
Com base na listagem dos casos de uso, desenvolver o diagrama e subir dentro da pasta.

**Comment by GabrielAlves027** [comment]
Utilizando da ferramenta proporcionada pelo site https://online.visual-paradigm.com/pt/ , nós elaboramos o seguinte Diagrama de Casos de Uso: https://github.com/Milenxsz/ES2/blob/main/Doc/CasoDeUso/Diagrama_CasosDeUso.jpg
