### ISSUE TITLE
Casos de Usos

### ISSUE THREAD

**Issue by Lflickr** [Milenxsz/ES2#2]
Listagem dos casos de uso
excluir cadastros basicos e logins
foco nas dores a ser resolvidas(o que apresetar em 5 minutos)

**Comment by Lflickr** [comment]
Atualização dos [casos de uso](https://github.com/Milenxsz/ES2/blob/main/README.md)

**Comment by GabrielAlves027** [comment]
Link para a listagem dos Casos de Uso: https://github.com/Milenxsz/ES2/blob/main/Doc/CasoDeUso/Casos_de_Uso.md
